### PR TITLE
Fix for #20. Remove all subclasses when getting attributes.

### PR DESCRIPTION
**Pull request by andyward**
Regenerated `SchemaInfo.Attributes.g.cs` after fix & bumped version.

I didn't commit the Markdown documentation changes triggered by regenerating the Schema as I didn't want to  complicate this PR - I think they are from recent changes not this change as no public signatures have changed.

### CODE REVIEW

**Comment by andyward** [comment]
@CBenghi Can you pull this PR if you get 5 mins?

**Comment by andyward** [comment]
Hi @CBenghi - it looks like the publish step on the build did not run - so build 1.0.56 is not in Nuget.

Looks like this is down to build.yaml excluding the Publish step when ` github.event_name != 'pull_request'` - See https://github.com/buildingSMART/IDS-Audit-tool/commit/49ea2448d2b23050ed0719ff1b7cade8a91a228c

**Comment by CBenghi** [comment]
I'll fix today

**Comment by CBenghi** [comment]
Hi Andy, I'm looking at this now.
Since I can't manage secrets on this repository, I'm publishing from my fork.
It should be fixed in a few moments.

**Pull request merged**
